#!/bin/bash

set -ex

STATS="$1/stats"

for stats in "$STATS"/*mds*/stats.db; do
	"$(dirname "$0")/clients" "$stats"
	"$(dirname "$0")/mdsmem" "$stats"
done

"$(dirname "$0")/mds-imported-inodes" "$STATS"
"$(dirname "$0")/mds-inode-cache" "$STATS"
"$(dirname "$0")/mds-memory" "$STATS"
"$(dirname "$0")/mds-requests" "$STATS"
"$(dirname "$0")/mds-throughput" "$STATS"
"$(dirname "$0")/mds-caps" "$STATS"
"$(dirname "$0")/mds-inode-expired" "$STATS"
"$(dirname "$0")/mds-strays" "$STATS"
"$(dirname "$0")/mds-objecter-op_w" "$STATS"
